"use client";
import { useState } from "react";
import { ArrowUpRight, ArrowRight, Layers, ShieldCheck } from "lucide-react";
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, CartesianGrid, BarChart, Bar, ReferenceLine } from "recharts";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { SectionCard } from "@/components/shared/section-card";
import type { AllocationResearch, AllocationExperiment } from "@/lib/allocation-types";
const pct = (n: number | null) => n === null ? "Not recorded" : `${n >= 0 ? "+" : ""}${(n * 100).toFixed(2)}%`;
const points = (n: number) => `${n >= 0 ? "+" : ""}${(n * 100).toFixed(2)} pp`;
const color = (n: number | null) => n !== null && n < 0 ? "text-bear" : "text-ink";
const chart = {allocator: "hsl(var(--action))", reference: "hsl(var(--graphite))", grid: "hsl(var(--rule))"};
export function AllocationDesk({data}: {data: AllocationResearch}) {
  const [id, setId] = useState(data.default_id);
  const e = data.experiments.find(x => x.id === id)!;
  const allocator = e.arms.find(a => a.id === "allocator_only")!;
  const hold = e.arms.find(a => a.id === "continuous_strict_hold")!;
  const uncertain = !e.ci || (e.ci[0] <= 0 && e.ci[1] >= 0);
  return <div className="space-y-8">
    <header className="fade-up space-y-4 border-b pb-6">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Portfolio research · US / USD</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-ink md:text-4xl">Allocation</h1><p className="mt-2 max-w-2xl text-sm text-graphite">Follow the price trend. See what AI keeps, what it rejects, and what the evidence supports.</p></div><span className="inline-flex items-center gap-2 rounded border bg-secondary px-3 py-2 text-xs text-ink"><ShieldCheck className="size-4" aria-hidden />Reliability unconfirmed</span></div>
      <div className="flex flex-wrap items-center gap-2 text-micro text-graphite"><span>12-month momentum</span><ArrowRight className="size-3" aria-hidden /><span>Top 3</span><ArrowRight className="size-3" aria-hidden /><span>Equal one-third sleeves</span><span className="ml-2 rounded bg-secondary px-2 py-1">Historical research · no live orders</span></div>
    </header>
    <Tabs defaultValue="research"><TabsList aria-label="Allocation view"><TabsTrigger value="research">Historical research</TabsTrigger><TabsTrigger value="snapshot">Current snapshot</TabsTrigger></TabsList>
      <TabsContent value="research" className="space-y-8">
        <section className="flex flex-wrap items-end justify-between gap-4"><div><label htmlFor="experiment" className="eyebrow block">Frozen experiment</label><select id="experiment" value={id} onChange={ev => setId(ev.target.value)} className="mt-2 max-w-full rounded border bg-card px-3 py-2 text-sm text-ink focus-visible:outline-action">{data.experiments.map(x => <option key={x.id} value={x.id}>{x.label}</option>)}</select></div><div className="text-right text-micro text-graphite"><p className="num">{e.start} → {e.end}</p><p>{e.periods} {e.kind === "monthly" ? "monthly periods" : "non-overlapping episodes"} · {e.cost_bps} bps / side</p></div></section>
        <div className="grid gap-5 border-y py-5 sm:grid-cols-3"><Metric label="Allocator net return" value={pct(allocator.net_return)} /><Metric label="Continuous hold" value={pct(hold.net_return)} /><Metric label="Observed excess vs hold" value={points(e.excess_vs_hold)} note="Cumulative return difference in percentage points" /></div>
        <SectionCard title="Separate the components" description="Compare strategies only inside this selected protocol."><div role="region" aria-label="Strategy comparison" tabIndex={0} className="overflow-x-auto rounded border"><table className="w-full min-w-[650px] text-sm"><thead className="border-b bg-secondary text-left text-micro text-graphite"><tr>{["Strategy", "Net return", "Max drawdown", "Mean exposure"].map(x => <th key={x} className="px-4 py-3 font-medium">{x}</th>)}</tr></thead><tbody>{e.arms.map(a => <tr key={a.id} className="border-b last:border-0"><th className="px-4 py-3 text-left font-medium text-ink">{a.label}</th>{a.status === "not_tested" ? <td colSpan={3} className="px-4 py-3 text-graphite">Not tested in this experiment</td> : <><td className={`num px-4 py-3 ${color(a.net_return)}`}>{pct(a.net_return)}</td><td className={`num px-4 py-3 ${color(a.drawdown)}`}>{pct(a.drawdown)}</td><td className="num px-4 py-3 text-graphite">{a.mean_exposure === null ? "Not recorded" : `${(a.mean_exposure * 100).toFixed(1)}%`}</td></>}</tr>)}</tbody></table></div><p className="mt-2 text-micro text-graphite">Drawdown: {e.drawdown_basis}. Missing metrics are not zero.</p></SectionCard>
        <SectionCard title="The path matters" description={`Wealth starts at 100. ${e.kind === "monthly" ? "Monthly" : "Episode-end"} observations; reference is ${e.reference_label.toLowerCase()}.`}><WealthChart experiment={e} /><p className="mt-2 text-micro text-graphite">Allocator ends at {e.curve.at(-1)!.allocator.toFixed(1)}; {e.reference_label.toLowerCase()} at {e.curve.at(-1)!.reference.toFixed(1)}. This chart is not a daily equity series.</p></SectionCard>
        <SectionCard title="What the evidence supports" description="Historical performance is an observation, not a confirmed edge."><div className="grid gap-5 rounded border p-5 md:grid-cols-2"><div><p className="eyebrow">Paired 95% interval</p><p className="num mt-2 text-lg text-ink">{e.ci ? `[${e.ci[0].toFixed(5)}, ${e.ci[1].toFixed(5)}]` : "Unavailable"}</p><p className="mt-1 text-micro text-graphite">Mean {e.kind === "monthly" ? "monthly" : "episode"} log excess vs {e.ci_reference.toLowerCase()}.</p><p className="mt-3 text-sm text-ink">{uncertain ? "No demonstrated excess-return edge." : "Positive interval in this historical comparison; external validation remains incomplete."}</p></div><div><p className="eyebrow">Sample and scope</p><p className="mt-2 text-sm text-ink">Effective period count: <span className="num">{e.effective_n}</span></p><p className="mt-1 text-micro text-graphite">A temporal count is not a count of independent market regimes.</p><ul className="mt-3 space-y-2 text-micro text-graphite">{data.limitations.map(x => <li key={x}>• {x}</li>)}</ul></div></div></SectionCard>
        <SectionCard title="Robustness checks" description="Original eight-stock monthly research; these diagnostics are separate from the selected episode protocol."><div className="grid gap-5 rounded border p-5 md:grid-cols-2"><div><p className="eyebrow">Rolling two-year windows · 20 bps</p><p className="num mt-2 text-xl text-ink">{data.robustness.rolling_wins} / {data.robustness.rolling_windows} ahead of hold</p><p className="mt-2 text-micro text-graphite">Worst relative wealth advantage: {pct(data.robustness.rolling_min)}. Windows overlap; this is not a forecast success rate.</p></div><div><p className="eyebrow">Best-month sensitivity · original 10 bps</p><p className="mt-2 text-sm text-ink">Omit the best {data.robustness.omitted_months} excess months from both arms:</p><p className="num mt-2 text-micro text-ink">Allocator {pct(data.robustness.omitted_allocator)} · Hold {pct(data.robustness.omitted_hold)}</p><p className="mt-2 text-micro text-graphite">The advantage disappears. Hindsight stress diagnosis, not an executable strategy.</p></div></div></SectionCard>
        <SectionCard title="Last historical selection" description={`Selected at ${e.last_selection.as_of}. This is not today's ranking or your holdings.`}><div className="flex flex-wrap gap-3">{e.last_selection.tickers.map(t => <a href={`/${t}`} key={t} className="flex items-center gap-3 rounded border px-4 py-3 text-sm text-ink hover:bg-secondary"><span className="num font-medium">{t}</span><span className="num text-graphite">33⅓%</span><ArrowUpRight className="size-3" aria-hidden /></a>)}</div></SectionCard>
        <details className="rounded border p-4"><summary className="cursor-pointer text-sm font-medium text-ink">Protocol and evidence</summary><div className="mt-4 space-y-3 text-micro text-graphite"><p>Universe: {e.universe.join(", ")}</p><p>{e.fee_basis}</p><p>Price basis: {e.price_basis.replaceAll("_", " ")}</p><ul className="space-y-2">{e.notes.map(n => <li key={n}>• {n}</li>)}</ul><p className="break-all num">Source SHA-256: {e.source_sha256}</p><a className="inline-block text-action underline underline-offset-4" href={`/allocation/evidence?id=${encodeURIComponent(e.id)}`}>Download this verified research view</a></div></details>
      </TabsContent>
      <TabsContent value="snapshot"><section className="rounded border p-6"><Layers className="size-6 text-graphite" aria-hidden /><h2 className="mt-3 text-lg font-semibold text-ink">No current plan connected</h2><p className="mt-2 max-w-xl text-sm text-graphite">{data.current_plan.reason} A valid plan needs completed inputs from one common session. Historical selections cannot stand in for current target weights.</p><p className="mt-4 text-micro text-graphite">Forward research is not activated. No orders or portfolio changes are made from this page.</p></section></TabsContent>
    </Tabs>
  </div>;
}
function Metric({label,value,note}: {label:string;value:string;note?:string}) {return <div><p className="eyebrow">{label}</p><p className="num mt-2 text-2xl font-medium tracking-tight text-ink">{value}</p>{note && <p className="mt-1 text-micro text-graphite">{note}</p>}</div>;}
function WealthChart({experiment:e}: {experiment:AllocationExperiment}) {
  const tooltip = {background:"hsl(var(--card))",border:"1px solid hsl(var(--rule))",borderRadius:6,color:"hsl(var(--ink))",fontSize:12};
  return <div><div className="mb-3 flex flex-wrap gap-4 text-micro text-graphite"><span><span style={{color:chart.allocator}}>━</span> Allocator</span><span>┄ {e.reference_label}</span></div><div className="h-64 w-full" role="img" aria-label={`Cumulative wealth at ${e.kind === "monthly" ? "monthly" : "episode"} observations, allocator versus ${e.reference_label}`}><ResponsiveContainer width="100%" height="100%"><LineChart data={e.curve} margin={{left:0,right:12,top:5,bottom:0}}><CartesianGrid stroke={chart.grid} vertical={false} /><XAxis dataKey="date" tickFormatter={x => String(x).slice(0,7)} minTickGap={40} tick={{fontSize:11,fill:chart.reference}} /><YAxis width={48} tick={{fontSize:11,fill:chart.reference}} /><Tooltip contentStyle={tooltip} formatter={(v:number|string) => Number(v).toFixed(1)} /><Line type="linear" dataKey="allocator" name="Allocator" stroke={chart.allocator} dot={false} strokeWidth={2} isAnimationActive={false} /><Line type="linear" dataKey="reference" name={e.reference_label} stroke={chart.reference} strokeDasharray="5 4" dot={false} isAnimationActive={false} /></LineChart></ResponsiveContainer></div><p className="eyebrow mb-2 mt-5">Paired log excess by observation</p><div className="h-32 w-full" role="img" aria-label="Paired log excess by observation; values above zero favor allocator"><ResponsiveContainer width="100%" height="100%"><BarChart data={e.curve.slice(1)} margin={{right:12}}><XAxis dataKey="date" tickFormatter={x => String(x).slice(0,7)} minTickGap={40} tick={{fontSize:10,fill:chart.reference}} /><YAxis width={48} tick={{fontSize:10,fill:chart.reference}} /><ReferenceLine y={0} stroke={chart.reference} /><Tooltip contentStyle={tooltip} formatter={(v:number|string) => Number(v).toFixed(4)} /><Bar dataKey="log_excess" name="Log excess" fill={chart.allocator} isAnimationActive={false} /></BarChart></ResponsiveContainer></div></div>;
}
