import type { Metadata } from "next";
import Link from "next/link";
import { Activity } from "lucide-react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Stock Briefings",
  description: "Multi-agent AI analysis across fundamentals, technicals, sentiment, and macro.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className="min-h-screen font-sans">
        <header className="sticky top-0 z-40 border-b border-border/60 glass">
          <div className="container flex h-14 items-center justify-between">
            <Link href="/" className="flex items-center gap-2 font-semibold tracking-tight">
              <span className="grid size-7 place-items-center rounded-md bg-primary/15 text-primary ring-1 ring-primary/30">
                <Activity className="size-4" strokeWidth={2.5} />
              </span>
              <span>Briefings</span>
              <span className="hidden text-xs font-normal text-muted-foreground sm:inline">
                / multi-agent stock intelligence
              </span>
            </Link>
            <nav className="flex items-center gap-5 text-sm text-muted-foreground">
              <Link href="/" className="hover:text-foreground transition-colors">
                Tickers
              </Link>
              <a
                href="https://github.com"
                className="hover:text-foreground transition-colors"
                target="_blank"
                rel="noreferrer"
              >
                Docs
              </a>
            </nav>
          </div>
        </header>
        <main className="container py-8 md:py-12">{children}</main>
        <footer className="container border-t border-border/60 py-8 text-xs text-muted-foreground">
          Generated by a 4-layer agent pipeline · Not investment advice
        </footer>
      </body>
    </html>
  );
}
