"""Deterministic factor research slice.

This module is intentionally small and point-in-time safe:

* clean a local OHLC price series without filling missing prices;
* compute a fixed long-only time-series momentum signal from past closes;
* enter on the next bar's open and exit after a fixed number of bars;
* evaluate expanding walk-forward out-of-sample folds; and
* report gross and cost-adjusted returns side by side.

It is a research baseline, not a claim that momentum is profitable or ready for
live trading.  The fixed rule has no fitted parameters, so the walk-forward
split is used to keep the evaluation protocol honest and extensible rather than
to search for a best model.
"""

from __future__ import annotations

import math
from datetime import date
from pathlib import Path

import pandas as pd
from pydantic import BaseModel, Field

from . import stats

FACTOR_NAME = "long-only time-series momentum"


class FactorConfig(BaseModel):
    """Parameters for the fixed baseline factor."""

    lookback_bars: int = Field(default=20, gt=0)
    holding_bars: int = Field(default=20, gt=0)
    initial_train_bars: int = Field(default=252, gt=0)
    test_window_bars: int = Field(default=63, gt=0)
    cost_bps_per_side: float = Field(default=0.0, ge=0.0, lt=10_000.0)


class FactorTrade(BaseModel):
    """One non-overlapping long trade generated by the factor."""

    ticker: str
    fold: int
    signal_date: date
    entry_date: date
    exit_date: date
    momentum: float
    entry_price: float
    exit_price: float
    gross_return: float
    net_return: float


class FactorFold(BaseModel):
    """One expanding walk-forward test fold."""

    fold: int
    train_start: date
    train_end: date
    test_start: date
    test_end: date
    opportunities: int
    trades: int
    gross_return: float
    net_return: float


class FactorReport(BaseModel):
    """Serializable result of a single-ticker factor experiment."""

    factor: str = FACTOR_NAME
    hypothesis: str
    ticker: str
    config: FactorConfig
    data_start: date
    data_end: date
    oos_start: date
    oos_end: date
    clean_rows: int
    opportunities: int
    trades: int
    flat_opportunities: int
    active_rate: float | None
    gross_compound_return: float | None
    net_compound_return: float | None
    buy_and_hold_return: float | None
    gross_mean_trade_return: float | None
    net_mean_trade_return: float | None
    win_rate: float | None
    win_rate_ci_95: tuple[float, float] | None
    max_drawdown: float | None
    annualized_sharpe: float | None
    net_p_value: float | None
    folds: list[FactorFold]
    trade_log: list[FactorTrade]


def load_price_history(path: Path) -> pd.DataFrame:
    """Load and clean a local ``price_history.csv`` file."""

    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Price history not found: {path}")
    return clean_price_history(pd.read_csv(path))


def clean_price_history(frame: pd.DataFrame) -> pd.DataFrame:
    """Return sorted, deduplicated, usable OHLC rows.

    Invalid dates and non-positive open/close prices are dropped.  Missing
    prices are not forward-filled: inventing a price would create a false
    observation and could change a signal or a fill.
    """

    required = {"date", "open", "close"}
    missing = required.difference(frame.columns)
    if missing:
        names = ", ".join(sorted(missing))
        raise ValueError(f"Price history is missing required columns: {names}")

    cleaned = frame.copy()
    cleaned["date"] = pd.to_datetime(cleaned["date"], errors="coerce")
    for column in ("open", "close"):
        cleaned[column] = pd.to_numeric(cleaned[column], errors="coerce")

    cleaned = cleaned.dropna(subset=["date", "open", "close"])
    cleaned = cleaned[(cleaned["open"] > 0) & (cleaned["close"] > 0)]
    cleaned = (
        cleaned.sort_values("date")
        .drop_duplicates(subset=["date"], keep="last")
        .reset_index(drop=True)
    )
    if cleaned.empty:
        raise ValueError("Price history contains no usable rows")
    return cleaned


def run_factor_backtest(
    ticker: str,
    price_history: pd.DataFrame,
    *,
    start: date | None = None,
    end: date | None = None,
    config: FactorConfig | None = None,
) -> FactorReport:
    """Run the fixed momentum factor on one ticker's local price history.

    The signal is calculated from the close on ``signal_date``.  The trade
    enters at the next trading bar's open and exits at the close after
    ``holding_bars`` bars.  Candidate signal dates advance by the holding
    period, so active trades never overlap.
    """

    config = config or FactorConfig()
    if config.test_window_bars <= config.holding_bars:
        raise ValueError("test_window_bars must be greater than holding_bars")

    frame = clean_price_history(price_history)
    if start is not None:
        frame = frame[frame["date"] >= pd.Timestamp(start)]
    if end is not None:
        frame = frame[frame["date"] <= pd.Timestamp(end)]
    frame = frame.reset_index(drop=True)

    minimum_rows = config.initial_train_bars + config.holding_bars + 1
    if len(frame) < minimum_rows:
        raise ValueError(
            f"Need at least {minimum_rows} clean rows for the configured warm-up "
            f"and holding period; found {len(frame)}"
        )

    frame["momentum"] = frame["close"].pct_change(config.lookback_bars)
    folds: list[FactorFold] = []
    trades: list[FactorTrade] = []
    opportunities = 0
    flat_opportunities = 0
    test_start_index = config.initial_train_bars
    fold_number = 1
    last_test_end_index: int | None = None

    while test_start_index + config.holding_bars < len(frame):
        test_end_index = min(
            test_start_index + config.test_window_bars,
            len(frame),
        )
        if test_end_index - test_start_index <= config.holding_bars:
            break

        fold_trades: list[FactorTrade] = []
        fold_opportunities = 0
        last_signal_index = test_end_index - config.holding_bars
        for signal_index in range(
            test_start_index,
            last_signal_index,
            config.holding_bars,
        ):
            fold_opportunities += 1
            opportunities += 1
            momentum = frame.at[signal_index, "momentum"]
            if pd.isna(momentum) or momentum <= 0:
                flat_opportunities += 1
                continue

            entry_index = signal_index + 1
            exit_index = entry_index + config.holding_bars - 1
            entry_price = float(frame.at[entry_index, "open"])
            exit_price = float(frame.at[exit_index, "close"])
            gross_return = (exit_price / entry_price) - 1.0
            net_return = _net_return(gross_return, config.cost_bps_per_side)
            trade = FactorTrade(
                ticker=ticker.upper(),
                fold=fold_number,
                signal_date=_as_date(frame.at[signal_index, "date"]),
                entry_date=_as_date(frame.at[entry_index, "date"]),
                exit_date=_as_date(frame.at[exit_index, "date"]),
                momentum=float(momentum),
                entry_price=entry_price,
                exit_price=exit_price,
                gross_return=gross_return,
                net_return=net_return,
            )
            trades.append(trade)
            fold_trades.append(trade)

        train_start = _as_date(frame.at[0, "date"])
        train_end = _as_date(frame.at[test_start_index - 1, "date"])
        test_start = _as_date(frame.at[test_start_index, "date"])
        test_end = _as_date(frame.at[test_end_index - 1, "date"])
        folds.append(
            FactorFold(
                fold=fold_number,
                train_start=train_start,
                train_end=train_end,
                test_start=test_start,
                test_end=test_end,
                opportunities=fold_opportunities,
                trades=len(fold_trades),
                gross_return=_compound(t.gross_return for t in fold_trades),
                net_return=_compound(t.net_return for t in fold_trades),
            )
        )
        last_test_end_index = test_end_index
        test_start_index = test_end_index
        fold_number += 1

    if not folds or last_test_end_index is None:
        raise ValueError("No complete walk-forward test fold could be formed")

    gross_returns = [trade.gross_return for trade in trades]
    net_returns = [trade.net_return for trade in trades]
    wins = sum(return_ > 0 for return_ in net_returns)
    net_p_value = stats.t_test_vs_zero(net_returns)[1] if net_returns else None

    first_test_index = config.initial_train_bars
    buy_and_hold = (
        float(frame.at[last_test_end_index - 1, "close"])
        / float(frame.at[first_test_index, "close"])
        - 1.0
    )

    return FactorReport(
        hypothesis=(
            f"If {config.lookback_bars}-bar momentum is positive at the close, "
            f"the next {config.holding_bars}-bar long trade has positive return "
            "after costs."
        ),
        ticker=ticker.upper(),
        config=config,
        data_start=_as_date(frame.at[0, "date"]),
        data_end=_as_date(frame.at[len(frame) - 1, "date"]),
        oos_start=folds[0].test_start,
        oos_end=folds[-1].test_end,
        clean_rows=len(frame),
        opportunities=opportunities,
        trades=len(trades),
        flat_opportunities=flat_opportunities,
        active_rate=(len(trades) / opportunities) if opportunities else None,
        gross_compound_return=_compound(gross_returns) if gross_returns else None,
        net_compound_return=_compound(net_returns) if net_returns else None,
        buy_and_hold_return=buy_and_hold,
        gross_mean_trade_return=_mean(gross_returns),
        net_mean_trade_return=_mean(net_returns),
        win_rate=(wins / len(net_returns)) if net_returns else None,
        win_rate_ci_95=stats.wilson_interval(wins, len(net_returns)) if net_returns else None,
        max_drawdown=_max_drawdown(net_returns) if net_returns else None,
        annualized_sharpe=_annualized_sharpe(net_returns, config.holding_bars),
        net_p_value=net_p_value,
        folds=folds,
        trade_log=trades,
    )


def to_markdown(report: FactorReport) -> str:
    """Render the research result as an auditable Markdown memo."""

    config = report.config
    lines = [
        "# Momentum Factor Research Report",
        "",
        f"> **Hypothesis:** {report.hypothesis}",
        ">",
        "> This is a deterministic research baseline, not a live-trading recommendation.",
        "",
        "## Protocol",
        "",
        f"- Ticker: `{report.ticker}`",
        f"- Data: {report.data_start.isoformat()} → {report.data_end.isoformat()} ({report.clean_rows} clean rows)",
        f"- Out-of-sample: {report.oos_start.isoformat()} → {report.oos_end.isoformat()}",
        f"- Signal: positive {config.lookback_bars}-bar close-to-close momentum",
        f"- Execution: next-bar open → close after {config.holding_bars} bars",
        f"- Walk-forward: {config.initial_train_bars}-bar initial warm-up, {config.test_window_bars}-bar test windows",
        f"- Cost: {config.cost_bps_per_side:.1f} bps/side ({config.cost_bps_per_side * 2:.1f} bps round trip)",
        "",
        "## Metrics",
        "",
        "| Metric | Value |",
        "| --- | ---: |",
        f"| Opportunities | {report.opportunities} |",
        f"| Active trades | {report.trades} ({_fmt_pct(report.active_rate)} active) |",
        f"| Gross compound return | {_fmt_pct(report.gross_compound_return)} |",
        f"| Net compound return | {_fmt_pct(report.net_compound_return)} |",
        f"| Buy-and-hold over OOS window | {_fmt_pct(report.buy_and_hold_return)} |",
        f"| Mean trade return (gross / net) | {_fmt_pct(report.gross_mean_trade_return)} / {_fmt_pct(report.net_mean_trade_return)} |",
        f"| Win rate (95% Wilson CI) | {_fmt_pct(report.win_rate)} ({_fmt_ci(report.win_rate_ci_95)}) |",
        f"| Max drawdown (net) | {_fmt_pct(report.max_drawdown)} |",
        f"| Annualized Sharpe (net) | {_fmt_float(report.annualized_sharpe)} |",
        f"| Net mean-return p-value | {_fmt_float(report.net_p_value)} |",
        "",
        "## Walk-forward folds",
        "",
        "| Fold | Train | Test | Opportunities | Trades | Gross | Net |",
        "| ---: | --- | --- | ---: | ---: | ---: | ---: |",
    ]
    for fold in report.folds:
        lines.append(
            f"| {fold.fold} | {fold.train_start} → {fold.train_end} "
            f"| {fold.test_start} → {fold.test_end} | {fold.opportunities} "
            f"| {fold.trades} | {_fmt_pct(fold.gross_return)} | {_fmt_pct(fold.net_return)} |"
        )

    lines += [
        "",
        "## Audit notes",
        "",
        "- The signal uses only closes available on `signal_date`; entry starts on the next bar.",
        "- Trades are non-overlapping. Flat opportunities do not incur transaction costs.",
        "- Gross and net returns are shown separately; net applies the configured cost on both legs.",
        "- No parameter is fitted inside the test folds. The result is evidence about this rule on this data, not proof of a durable edge.",
    ]
    return "\n".join(lines) + "\n"


def _as_date(value) -> date:
    return pd.Timestamp(value).date()


def _net_return(gross_return: float, cost_bps_per_side: float) -> float:
    cost_rate = cost_bps_per_side / 10_000.0
    return (1.0 + gross_return) * (1.0 - cost_rate) ** 2 - 1.0


def _compound(returns) -> float:
    result = 1.0
    for return_ in returns:
        result *= 1.0 + return_
    return result - 1.0


def _mean(values: list[float]) -> float | None:
    return sum(values) / len(values) if values else None


def _max_drawdown(returns: list[float]) -> float:
    equity = 1.0
    peak = equity
    drawdown = 0.0
    for return_ in returns:
        equity *= 1.0 + return_
        peak = max(peak, equity)
        drawdown = min(drawdown, equity / peak - 1.0)
    return drawdown


def _annualized_sharpe(values: list[float], holding_bars: int) -> float | None:
    if len(values) < 2:
        return None
    mean = sum(values) / len(values)
    variance = sum((value - mean) ** 2 for value in values) / (len(values) - 1)
    if variance <= 0:
        return None
    return mean / math.sqrt(variance) * math.sqrt(252 / holding_bars)


def _fmt_pct(value: float | None) -> str:
    return "n/a" if value is None else f"{value * 100:.2f}%"


def _fmt_float(value: float | None) -> str:
    return "n/a" if value is None else f"{value:.3f}"


def _fmt_ci(value: tuple[float, float] | None) -> str:
    return "n/a" if value is None else f"{_fmt_pct(value[0])} → {_fmt_pct(value[1])}"
